### ISSUE TITLE
MPDD数据集

### ISSUE THREAD

**Issue by liuaohunter** [Haoyan-Guan/CAReg#3]
请问能提供一下MPDD数据集，支持集和数据处理的代码吗？

**Comment by ZongYingLi** [comment]
> 请问能提供一下MPDD数据集，支持集和数据处理的代码吗？

请问您找到了下载MPDD数据集的路径和数据处理代码吗，如果有的话请问能否也提供给我一下，十分感谢。

**Comment by liuaohunter** [comment]
https://github.com/stepanje/mpdd在这链接里下载，数据处理代码几乎和MVTec一样

**Comment by ZongYingLi** [comment]
> [https://github.com/stepanje/mpdd在这链接里下载，数据处理代码几乎和MVTec一样](https://github.com/stepanje/mpdd%E5%9C%A8%E8%BF%99%E9%93%BE%E6%8E%A5%E9%87%8C%E4%B8%8B%E8%BD%BD%EF%BC%8C%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86%E4%BB%A3%E7%A0%81%E5%87%A0%E4%B9%8E%E5%92%8CMVTec%E4%B8%80%E6%A0%B7)

好，我获取到了，谢谢你，请问你已经成功复现了RegAD的效果吗，大概训练模型用了多久呀（我的训练时间特别长，不知道是不是正常情况咧）

**Comment by liuaohunter** [comment]
复现了，结果差不多，时间长正常的，能跑通就行

**Comment by Harry-Bai** [comment]
您好，我用自己的数据集训练时遇到了如下报错，您可以帮忙看一下吗？
Getting transformed features...
Calculating distances...
Maximum distance from cluster centers is 1.31
initial embedding size :  (137984, 1536)
final embedding size :  (13798, 1536)
  0%|                                                                                                       | 0/10 [29:48<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 685, in <module>
    main()
  File "train.py", line 193, in main
    gt_list_px_lvl, gt_list_img_lvl, gt_list, gt_mask_list = test_patchcore2(models, inference_round, fixed_fewshot_list,
  File "train.py", line 673, in test_patchcore2
    anomaly_map = score_patches[:,0].reshape((28,28))
ValueError: cannot reshape array of size 1288 into shape (28,28)

**Comment by ZongYingLi** [comment]
> 您好，我用自己的数据集训练时遇到了如下报错，您可以帮忙看一下吗？ Getting transformed features... Calculating distances... Maximum distance from cluster centers is 1.31 initial embedding size : (137984, 1536) final embedding size : (13798, 1536) 0%| | 0/10 [29:48<?, ?it/s] Traceback (most recent call last): File "train.py", line 685, in main() File "train.py", line 193, in main gt_list_px_lvl, gt_list_img_lvl, gt_list, gt_mask_list = test_patchcore2(models, inference_round, fixed_fewshot_list, File "train.py", line 673, in test_patchcore2 anomaly_map = score_patches[:,0].reshape((28,28)) ValueError: cannot reshape array of size 1288 into shape (28,28)

请问你的数据集的图片宽高是多少

**Comment by Harry-Bai** [comment]
训练集是800×600，测试集是1004×620

**Comment by ZongYingLi** [comment]
> 训练集是800×600，测试集是1004×620

新的数据集和原数据的维度对不上，导致网络处理后的张量维度不同，reshape就报错了，可以看看 STN(query_img.to(device))的具体维度变化，修改一下网络层的参数

要么直接把reshape的维度改了，反正最后是为了还原成跟原图一样的维度

可以试试，感觉第二种修改简单些，但不知道对结果影响大不大，可以把还原后的图片可视化看一下再决定

**Comment by Harry-Bai** [comment]
好的，谢谢大佬指点

**Comment by ZongYingLi** [comment]
> 好的，谢谢大佬指点

没有没有，我是菜鸡，说的不一定对，可以试试

**Comment by Harry-Bai** [comment]
打扰您了，我想再问一下，原数据集的图片尺寸是多少呀

**Comment by Harry-Bai** [comment]
解决了，图片宽高保持一致即可
