### ISSUE TITLE
请问您使用python版本是多少啊？可以的话可以提供安装库的具体名称和版本吗？

### ISSUE THREAD

**Issue by liuyuha** [Haoyan-Guan/CAReg#5]

**Comment by ZongYingLi** [comment]
> _No description provided._

他在论文里提到RegAD是上一个工作，我在猜测会不会是用同一个环境 https://github.com/MediaBrain-SJTU/RegAD

**Comment by Haoyan-Guan** [comment]
Yes, please check it
